# Generated by Django 3.1.1 on 2020-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
