# Generated by Django 3.1.1 on 2020-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20201005_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
