# Generated by Django 3.1.1 on 2020-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_auto_20201005_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(default='123', max_length=15),
        ),
    ]
