# Generated by Django 3.1.1 on 2020-10-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20201005_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_shop',
            field=models.BooleanField(default=False),
        ),
    ]
