# Generated by Django 3.1.1 on 2020-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
