# Generated by Django 3.1.1 on 2020-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
