# Generated by Django 3.1.1 on 2020-10-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201024_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipment',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
