# Generated by Django 3.1.1 on 2020-10-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201024_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
