# Generated by Django 3.1.1 on 2020-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201025_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
