# Generated by Django 3.1.1 on 2020-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='credit_card_number',
            field=models.IntegerField(null=True),
        ),
    ]
