# Generated by Django 3.1.1 on 2020-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201026_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cvv',
            field=models.IntegerField(null=True),
        ),
    ]
