# Generated by Django 3.1.1 on 2020-10-26 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0009_auto_20201026_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'shop')},
        ),
    ]
