# Generated by Django 3.1.1 on 2020-10-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201026_1844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
